### ISSUE TITLE
Consider option to control cache on ivalidation

### ISSUE THREAD

**Issue by Felixoid** [Felixoid/zsh-hoco#2]
Currently, the cache is just dropped on each update.

It's possible to make it configurable to stay available forever in case of problems.

Upd: it looks to me that I found the best way to implement it is using the builtins, a good example is in [_perl_modules](https://github.com/zsh-users/zsh/blob/master/Completion/Unix/Type/_perl_modules#L37-L46) sources and following `_store_cache`, `_retrieve_cache`, and `_cache_invalid` functions

**Comment by varenc** [comment]
That would be nice, but as is I love this project! Thank you for making it.  Really seems like something that could be submitted upstream to zsh as well.

At the moment I'm using `HOCO_FUNCTIONS` to automatically add some hosts used by with my personal aliases from zsh history to host completion. It's pretty janky but it works great.  Thank you!

```zsh

function __listRecentHosts() {
  gtail -n 20000 ~/.zsh_history | ggrep -E ";(certs|certOwner|dnsAll)\s+\w{2,}" | hck -d ";" -f 2 | hck -d "\s+" -f "2" | sort | guniq
}
HOCO_FUNCTIONS=(__listRecentHosts)
source ~/.config/hoco.zsh

```

**Comment by Felixoid** [comment]
You can try a new version from #4 before it's merged.
